apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-lag-exporter
  labels:
    app: kafka-lag-exporter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka-lag-exporter
  template:
    metadata:
      labels:
        app: kafka-lag-exporter
    spec:
      containers:
        - name: kafka-lag-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9090
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          readinessProbe:
            httpGet: { path: /healthz, port: metrics }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: metrics }
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}