apiVersion: apps/v1
kind: Deployment
metadata:
  name: reaper
  labels:
    app: reaper
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: reaper
  template:
    metadata:
      labels:
        app: reaper
    spec:
      containers:
        - name: reaper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
