apiVersion: v1
kind: Service
metadata:
  name: mock-device
  labels:
    app: mock-device
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: mock-device
