// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID             uuid.UUID          `json:"id"`
	Type           string             `json:"type"`
	Tier           string             `json:"tier"`
	DeviceID       string             `json:"device_id"`
	State          string             `json:"state"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey string             `json:"idempotency_key"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	LastError      *string            `json:"last_error"`
	HeartbeatAt    pgtype.Timestamptz `json:"heartbeat_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
