// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Create a device row. ON CONFLICT DO NOTHING means submitting the same
	// device twice is harmless (we use this in `make seed`).
	CreateDevice(ctx context.Context, id string) (Device, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	GetDevice(ctx context.Context, id string) (Device, error)
	// Health check: read the columns the handler decides on.
	GetDeviceForHealthCheck(ctx context.Context, id string) (GetDeviceForHealthCheckRow, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error)
	IncrementJobAttempts(ctx context.Context, id uuid.UUID) (Job, error)
	// Alert: record an alert row.
	InsertAlert(ctx context.Context, arg InsertAlertParams) (Alert, error)
	// Remote command: audit log entry.
	InsertCommandAudit(ctx context.Context, arg InsertCommandAuditParams) (CommandAudit, error)
	// ===== Phase 1 additions =====
	// Telemetry: insert one aggregate row.
	InsertDeviceMetric(ctx context.Context, arg InsertDeviceMetricParams) (DeviceMetric, error)
	// Firmware: record an attempt. Always inserts; we keep history.
	InsertFirmwareAttempt(ctx context.Context, arg InsertFirmwareAttemptParams) (FirmwareHistory, error)
	// Find RUNNING jobs whose heartbeat is older than `staleness`. The
	// FOR UPDATE SKIP LOCKED clause is critical: multiple reaper instances
	// (or the reaper running concurrently with workers) must not fight over
	// the same row. SKIP LOCKED makes them cooperate naturally.
	ReapStaleJobs(ctx context.Context, arg ReapStaleJobsParams) ([]ReapStaleJobsRow, error)
	// Reset a stale RUNNING job back to QUEUED so it'll be picked up again.
	// Increments attempts so we don't retry forever.
	RequeueJob(ctx context.Context, id uuid.UUID) (Job, error)
	// Health check: bump last_seen.
	TouchDevice(ctx context.Context, id string) error
	// Update the device's recorded firmware version after a successful update.
	UpdateDeviceFirmware(ctx context.Context, arg UpdateDeviceFirmwareParams) error
	UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
