// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Create a device row. ON CONFLICT DO NOTHING means submitting the same
	// device twice is harmless (we use this in `make seed`).
	CreateDevice(ctx context.Context, id string) (Device, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	GetDevice(ctx context.Context, id string) (Device, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error)
	IncrementJobAttempts(ctx context.Context, id uuid.UUID) (Job, error)
	UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
