// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id) VALUES ($1)
ON CONFLICT (id) DO NOTHING
RETURNING id, created_at, last_seen_at, firmware_version
`

// Create a device row. ON CONFLICT DO NOTHING means submitting the same
// device twice is harmless (we use this in `make seed`).
func (q *Queries) CreateDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.FirmwareVersion,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (type, tier, device_id, payload, idempotency_key, max_attempts)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at
`

type CreateJobParams struct {
	Type           string `json:"type"`
	Tier           string `json:"tier"`
	DeviceID       string `json:"device_id"`
	Payload        []byte `json:"payload"`
	IdempotencyKey string `json:"idempotency_key"`
	MaxAttempts    int32  `json:"max_attempts"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Type,
		arg.Tier,
		arg.DeviceID,
		arg.Payload,
		arg.IdempotencyKey,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, created_at, last_seen_at, firmware_version FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.FirmwareVersion,
	)
	return i, err
}

const getDeviceForHealthCheck = `-- name: GetDeviceForHealthCheck :one
SELECT id, last_seen_at, firmware_version
FROM devices WHERE id = $1
`

type GetDeviceForHealthCheckRow struct {
	ID              string     `json:"id"`
	LastSeenAt      *time.Time `json:"last_seen_at"`
	FirmwareVersion *string    `json:"firmware_version"`
}

// Health check: read the columns the handler decides on.
func (q *Queries) GetDeviceForHealthCheck(ctx context.Context, id string) (GetDeviceForHealthCheckRow, error) {
	row := q.db.QueryRow(ctx, getDeviceForHealthCheck, id)
	var i GetDeviceForHealthCheckRow
	err := row.Scan(&i.ID, &i.LastSeenAt, &i.FirmwareVersion)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at FROM jobs WHERE idempotency_key = $1 AND type = $2
`

type GetJobByIdempotencyKeyParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	Type           string `json:"type"`
}

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, arg.IdempotencyKey, arg.Type)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementJobAttempts = `-- name: IncrementJobAttempts :one
UPDATE jobs
SET attempts = attempts + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at
`

func (q *Queries) IncrementJobAttempts(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, incrementJobAttempts, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAlert = `-- name: InsertAlert :one
INSERT INTO alerts (device_id, severity, message, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, device_id, severity, message, payload, acknowledged, created_at
`

type InsertAlertParams struct {
	DeviceID string `json:"device_id"`
	Severity string `json:"severity"`
	Message  string `json:"message"`
	Payload  []byte `json:"payload"`
}

// Alert: record an alert row.
func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, insertAlert,
		arg.DeviceID,
		arg.Severity,
		arg.Message,
		arg.Payload,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Severity,
		&i.Message,
		&i.Payload,
		&i.Acknowledged,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommandAudit = `-- name: InsertCommandAudit :one
INSERT INTO command_audit (device_id, command, arguments, result, response, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, device_id, command, arguments, result, response, duration_ms, executed_at
`

type InsertCommandAuditParams struct {
	DeviceID   string `json:"device_id"`
	Command    string `json:"command"`
	Arguments  []byte `json:"arguments"`
	Result     string `json:"result"`
	Response   []byte `json:"response"`
	DurationMs int32  `json:"duration_ms"`
}

// Remote command: audit log entry.
func (q *Queries) InsertCommandAudit(ctx context.Context, arg InsertCommandAuditParams) (CommandAudit, error) {
	row := q.db.QueryRow(ctx, insertCommandAudit,
		arg.DeviceID,
		arg.Command,
		arg.Arguments,
		arg.Result,
		arg.Response,
		arg.DurationMs,
	)
	var i CommandAudit
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Command,
		&i.Arguments,
		&i.Result,
		&i.Response,
		&i.DurationMs,
		&i.ExecutedAt,
	)
	return i, err
}

const insertDeviceMetric = `-- name: InsertDeviceMetric :one

INSERT INTO device_metrics (device_id, metric_at, avg_value, sample_count)
VALUES ($1, $2, $3, $4)
RETURNING id, device_id, metric_at, avg_value, sample_count, created_at
`

type InsertDeviceMetricParams struct {
	DeviceID    string    `json:"device_id"`
	MetricAt    time.Time `json:"metric_at"`
	AvgValue    float64   `json:"avg_value"`
	SampleCount int32     `json:"sample_count"`
}

// ===== Phase 1 additions =====
// Telemetry: insert one aggregate row.
func (q *Queries) InsertDeviceMetric(ctx context.Context, arg InsertDeviceMetricParams) (DeviceMetric, error) {
	row := q.db.QueryRow(ctx, insertDeviceMetric,
		arg.DeviceID,
		arg.MetricAt,
		arg.AvgValue,
		arg.SampleCount,
	)
	var i DeviceMetric
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.MetricAt,
		&i.AvgValue,
		&i.SampleCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertFirmwareAttempt = `-- name: InsertFirmwareAttempt :one
INSERT INTO firmware_history (device_id, target_version, state, failure_reason)
VALUES ($1, $2, $3, $4)
RETURNING id, device_id, target_version, state, failure_reason, attempted_at
`

type InsertFirmwareAttemptParams struct {
	DeviceID      string  `json:"device_id"`
	TargetVersion string  `json:"target_version"`
	State         string  `json:"state"`
	FailureReason *string `json:"failure_reason"`
}

// Firmware: record an attempt. Always inserts; we keep history.
func (q *Queries) InsertFirmwareAttempt(ctx context.Context, arg InsertFirmwareAttemptParams) (FirmwareHistory, error) {
	row := q.db.QueryRow(ctx, insertFirmwareAttempt,
		arg.DeviceID,
		arg.TargetVersion,
		arg.State,
		arg.FailureReason,
	)
	var i FirmwareHistory
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.TargetVersion,
		&i.State,
		&i.FailureReason,
		&i.AttemptedAt,
	)
	return i, err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen_at = NOW() WHERE id = $1
`

// Health check: bump last_seen.
func (q *Queries) TouchDevice(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchDevice, id)
	return err
}

const updateDeviceFirmware = `-- name: UpdateDeviceFirmware :exec
UPDATE devices SET firmware_version = $2 WHERE id = $1
`

type UpdateDeviceFirmwareParams struct {
	ID              string  `json:"id"`
	FirmwareVersion *string `json:"firmware_version"`
}

// Update the device's recorded firmware version after a successful update.
func (q *Queries) UpdateDeviceFirmware(ctx context.Context, arg UpdateDeviceFirmwareParams) error {
	_, err := q.db.Exec(ctx, updateDeviceFirmware, arg.ID, arg.FirmwareVersion)
	return err
}

const updateJobState = `-- name: UpdateJobState :one
UPDATE jobs
SET state = $2,
    updated_at = NOW(),
    started_at = COALESCE(started_at, CASE WHEN $2 = 'RUNNING' THEN NOW() ELSE NULL END),
    finished_at = CASE WHEN $2 IN ('SUCCESS','FAILED') THEN NOW() ELSE finished_at END,
    last_error = COALESCE($3, last_error)
WHERE id = $1
RETURNING id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at
`

type UpdateJobStateParams struct {
	ID        uuid.UUID `json:"id"`
	State     string    `json:"state"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobState, arg.ID, arg.State, arg.LastError)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
