// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id) VALUES ($1)
ON CONFLICT (id) DO NOTHING
RETURNING id, created_at
`

// Create a device row. ON CONFLICT DO NOTHING means submitting the same
// device twice is harmless (we use this in `make seed`).
func (q *Queries) CreateDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, id)
	var i Device
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (type, tier, device_id, payload, idempotency_key, max_attempts)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at
`

type CreateJobParams struct {
	Type           string `json:"type"`
	Tier           string `json:"tier"`
	DeviceID       string `json:"device_id"`
	Payload        []byte `json:"payload"`
	IdempotencyKey string `json:"idempotency_key"`
	MaxAttempts    int32  `json:"max_attempts"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Type,
		arg.Tier,
		arg.DeviceID,
		arg.Payload,
		arg.IdempotencyKey,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, created_at FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByIdempotencyKey = `-- name: GetJobByIdempotencyKey :one
SELECT id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at FROM jobs WHERE idempotency_key = $1 AND type = $2
`

type GetJobByIdempotencyKeyParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	Type           string `json:"type"`
}

func (q *Queries) GetJobByIdempotencyKey(ctx context.Context, arg GetJobByIdempotencyKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIdempotencyKey, arg.IdempotencyKey, arg.Type)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementJobAttempts = `-- name: IncrementJobAttempts :one
UPDATE jobs
SET attempts = attempts + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at
`

func (q *Queries) IncrementJobAttempts(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, incrementJobAttempts, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJobState = `-- name: UpdateJobState :one
UPDATE jobs
SET state = $2,
    updated_at = NOW(),
    started_at = COALESCE(started_at, CASE WHEN $2 = 'RUNNING' THEN NOW() ELSE NULL END),
    finished_at = CASE WHEN $2 IN ('SUCCESS','FAILED') THEN NOW() ELSE finished_at END,
    last_error = COALESCE($3, last_error)
WHERE id = $1
RETURNING id, type, tier, device_id, state, payload, idempotency_key, attempts, max_attempts, last_error, heartbeat_at, started_at, finished_at, created_at, updated_at
`

type UpdateJobStateParams struct {
	ID        uuid.UUID `json:"id"`
	State     string    `json:"state"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobState, arg.ID, arg.State, arg.LastError)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Tier,
		&i.DeviceID,
		&i.State,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
