apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-standard
  labels:
    app: worker-standard
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: worker-standard
  template:
    metadata:
      labels:
        app: worker-standard
    spec:
      containers:
        - name: worker-standard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics                          # observability /metrics endpoint
              containerPort: 9090
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
